# Generated by Django 2.1.1 on 2018-09-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_model',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AlterUniqueTogether(
            name='device_model',
            unique_together={('vendor', 'models', 'img')},
        ),
    ]
