# Generated by Django 2.1.1 on 2018-09-10 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20180904_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetspace',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Asset', verbose_name='机柜空间'),
        ),
    ]
