# Generated by Django 2.1.1 on 2018-11-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20181109_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='toAsset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Asset'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='log_type',
            field=models.CharField(choices=[('1', '设备'), ('2', '部件')], max_length=128, verbose_name='日志类型'),
        ),
    ]
