# Generated by Django 2.1.1 on 2018-11-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20181109_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='log_type',
            field=models.CharField(choices=[('1', '普通'), ('2', '部件')], max_length=128, verbose_name='日志类型'),
        ),
    ]
