# Generated by Django 2.1.1 on 2018-09-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180913_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='cabinet_heigh',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='机柜高度'),
        ),
    ]
