# Generated by Django 2.1.1 on 2018-11-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20181109_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='log_type',
        ),
    ]
