# Generated by Django 2.1.1 on 2018-09-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20180913_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cab_location',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='机柜位置'),
        ),
        migrations.AddField(
            model_name='asset',
            name='height',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='高度'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cabinet_height',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='机柜高度'),
        ),
        migrations.AlterField(
            model_name='cabinetspace',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cabinet', verbose_name='所在机柜'),
        ),
    ]
