# Generated by Django 2.1.1 on 2018-09-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20180919_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetspace',
            name='cabinet_location',
            field=models.CharField(blank=True, choices=[('1', '1U'), ('2', '2U'), ('3', '3U'), ('4', '4U'), ('5', '5U'), ('6', '6U'), ('7', '7U'), ('8', '8U'), ('9', '9U'), ('10', '10U'), ('11', '11U'), ('12', '12U'), ('13', '13U'), ('14', '14U'), ('15', '15U'), ('16', '16U'), ('17', '17U'), ('18', '18U'), ('19', '19U'), ('20', '20U'), ('21', '21U'), ('22', '22U'), ('23', '23U'), ('24', '24U'), ('25', '25U'), ('26', '26U'), ('27', '27U'), ('28', '28U'), ('29', '29U'), ('30', '30U'), ('31', '31U'), ('32', '32U'), ('33', '33U'), ('34', '34U'), ('35', '35U'), ('36', '36U'), ('37', '37U'), ('38', '38U'), ('39', '39U'), ('40', '40U'), ('41', '41U'), ('42', '42U')], max_length=64, verbose_name='机柜位置'),
        ),
    ]
